import type { Metadata } from "next";
import { NextAuthProvider } from "@/components/SessionProvider"; // Import the wrapper
import "./globals.css";

export const metadata: Metadata = {
  title: "Call Center Module",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextAuthProvider>
           {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}